const ZH_CN_ACCESSIBILITY_COPY = {
  accessibility: {
    titleBar: {
      minimize: "最小化窗口",
      maximize: "最大化窗口",
      restore: "还原窗口",
      close: "关闭窗口",
    },
    widget: {
      currentApp: (appName: string) => `当前应用：${appName}`,
      openMainWindow: "打开主窗口",
      collapse: "收起挂件",
      expand: "展开挂件",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "收起挂件" : "展开挂件"}，${statusTitle}`,
    },
    data: {
      trendSummary: "趋势摘要",
      trendRange: "选择趋势范围",
      shorterTrendRange: "查看更短趋势范围",
      longerTrendRange: "查看更长趋势范围",
      heatmapRange: "选择热力图范围",
      earlierRange: "查看更早范围",
      newerRange: "查看更新范围",
      appTrendRange: "选择应用趋势范围",
      shorterAppTrendRange: "查看更短应用趋势范围",
      longerAppTrendRange: "查看更长应用趋势范围",
      openTrendRangePicker: "打开趋势范围选择",
      resetTrendRange: "恢复近 7 天",
      previousPickerMode: "上一个范围模式",
      nextPickerMode: "下一个范围模式",
      previousPickerMonth: "上个月",
      nextPickerMonth: "下个月",
    },
    date: {
      previousMonth: "上个月",
      nextMonth: "下个月",
    },
    history: {
      previousMonth: "上个月",
      nextMonth: "下个月",
      decreaseMinDuration: "减少最短时长 1 分钟",
      increaseMinDuration: "增加最短时长 1 分钟",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "收起" : "展开"} ${appName} 的标题详情`
      ),
    },
    settings: {
      toggleTrackingPaused: "切换暂停追踪",
      toggleMinimizeToWidget: "切换最小化到挂件",
      toggleCloseToTray: "切换关闭到托盘",
      toggleBackgroundOptimization: "切换低耗后台",
      toggleLaunchAtLogin: "切换开机自启动",
      toggleStartMinimized: "切换启动时最小化",
      toggleWebActivity: "切换网页同步",
      openWebActivityHelp: "打开网页同步使用说明",
      copyWebActivityPort: "复制网页同步端口",
      copyWebActivityToken: "复制网页同步 Token",
      toggleRemoteStatusBridge: "切换远程推送",
      generateServiceToken: "随机生成 Token",
      showServiceToken: "显示 Token",
      hideServiceToken: "隐藏 Token",
      showRemoteMachineId: "显示本机标识",
      hideRemoteMachineId: "隐藏本机标识",
      colorScheme: "配色方案",
    },
    tools: {
      openStatusChip: "打开工具页面状态",
      createReminder: "创建提醒",
      cancelReminder: "取消提醒",
      startTimer: "开始计时器",
      pauseTimer: "暂停计时器",
      resumeTimer: "继续计时器",
      resetTimer: "重置计时器",
      addTimerLap: "添加分段",
      startPomodoro: "开始番茄钟",
      pausePomodoro: "暂停番茄钟",
      resumePomodoro: "继续番茄钟",
      skipPomodoroPhase: "跳过番茄钟阶段",
      resetPomodoro: "重置番茄钟",
      restorePomodoroDefaults: "恢复番茄钟默认时长",
      decreaseDuration: (label: string) => `${label}减少 1 分钟`,
      increaseDuration: (label: string) => `${label}增加 1 分钟`,
    },
    color: {
      color: "颜色",
      eyedropper: "取色器",
      eyedropperUnsupported: "当前环境不支持取色器",
      colorPicker: "颜色选择器",
      colorFormat: "颜色格式",
    },
  },
};

const EN_US_ACCESSIBILITY_COPY = {
  accessibility: {
    titleBar: {
      minimize: "Minimize window",
      maximize: "Maximize window",
      restore: "Restore window",
      close: "Close window",
    },
    widget: {
      currentApp: (appName: string) => `Current app: ${appName}`,
      openMainWindow: "Open main window",
      collapse: "Collapse widget",
      expand: "Expand widget",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "Collapse widget" : "Expand widget"}, ${statusTitle}`,
    },
    data: {
      trendSummary: "Trend summary",
      trendRange: "Select trend range",
      shorterTrendRange: "Show shorter trend range",
      longerTrendRange: "Show longer trend range",
      heatmapRange: "Select heatmap range",
      earlierRange: "Show earlier range",
      newerRange: "Show newer range",
      appTrendRange: "Select app trend range",
      shorterAppTrendRange: "Show shorter app trend range",
      longerAppTrendRange: "Show longer app trend range",
      openTrendRangePicker: "Open trend range picker",
      resetTrendRange: "Reset to last 7 days",
      previousPickerMode: "Previous range mode",
      nextPickerMode: "Next range mode",
      previousPickerMonth: "Previous month",
      nextPickerMonth: "Next month",
    },
    date: {
      previousMonth: "Previous month",
      nextMonth: "Next month",
    },
    history: {
      previousMonth: "Previous month",
      nextMonth: "Next month",
      decreaseMinDuration: "Decrease minimum duration by 1 minute",
      increaseMinDuration: "Increase minimum duration by 1 minute",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "Collapse" : "Expand"} title details for ${appName}`
      ),
    },
    settings: {
      toggleTrackingPaused: "Toggle pause tracking",
      toggleMinimizeToWidget: "Toggle minimize to widget",
      toggleCloseToTray: "Toggle close to tray",
      toggleBackgroundOptimization: "Toggle low-footprint background",
      toggleLaunchAtLogin: "Toggle launch at login",
      toggleStartMinimized: "Toggle start minimized",
      toggleWebActivity: "Toggle web sync",
      openWebActivityHelp: "Open web sync guide",
      copyWebActivityPort: "Copy web sync port",
      copyWebActivityToken: "Copy web sync Token",
      toggleRemoteStatusBridge: "Toggle remote push",
      generateServiceToken: "Generate token",
      showServiceToken: "Show token",
      hideServiceToken: "Hide token",
      showRemoteMachineId: "Show device ID",
      hideRemoteMachineId: "Hide device ID",
      colorScheme: "Color scheme",
    },
    tools: {
      openStatusChip: "Open tools status",
      createReminder: "Create reminder",
      cancelReminder: "Cancel reminder",
      startTimer: "Start timer",
      pauseTimer: "Pause timer",
      resumeTimer: "Resume timer",
      resetTimer: "Reset timer",
      addTimerLap: "Add lap",
      startPomodoro: "Start pomodoro",
      pausePomodoro: "Pause pomodoro",
      resumePomodoro: "Resume pomodoro",
      skipPomodoroPhase: "Skip pomodoro phase",
      resetPomodoro: "Reset pomodoro",
      restorePomodoroDefaults: "Restore pomodoro default durations",
      decreaseDuration: (label: string) => `Decrease ${label} by 1 minute`,
      increaseDuration: (label: string) => `Increase ${label} by 1 minute`,
    },
    color: {
      color: "Color",
      eyedropper: "Eyedropper",
      eyedropperUnsupported: "Eyedropper is unavailable",
      colorPicker: "Color picker",
      colorFormat: "Color format",
    },
  },
};

export const accessibilityCopy = {
  "zh-CN": ZH_CN_ACCESSIBILITY_COPY,
  "en-US": EN_US_ACCESSIBILITY_COPY,
} as const;
