const ZH_CN_CATEGORIES_COPY = {
  categories: {
    ai: "AI",
    custom: "自定义",
    short: {
      development: "开发",
      office: "办公",
      browser: "浏览",
      communication: "通讯",
      video: "视频",
      music: "音乐",
      game: "游戏",
      design: "设计",
      utility: "工具",
      other: "未分类",
      system: "系统",
    },
    development: "开发编码",
    office: "办公协作",
    browser: "浏览阅读",
    communication: "即时通讯",
    video: "视频内容",
    music: "音乐音频",
    game: "游戏",
    design: "设计创作",
    utility: "工具效率",
    system: "系统工具",
    other: "其他",
  },
};

const EN_US_CATEGORIES_COPY = {
  categories: {
    ai: "AI",
    custom: "Custom",
    short: {
      development: "Dev",
      office: "Office",
      browser: "Browser",
      communication: "Chat",
      video: "Video",
      music: "Music",
      game: "Games",
      design: "Design",
      utility: "Tools",
      other: "Other",
      system: "System",
    },
    development: "Development",
    office: "Office",
    browser: "Browser",
    communication: "Communication",
    video: "Video",
    music: "Music",
    game: "Games",
    design: "Design",
    utility: "Utilities",
    system: "System",
    other: "Other",
  },
};

export const categoriesCopy = {
  "zh-CN": ZH_CN_CATEGORIES_COPY,
  "en-US": EN_US_CATEGORIES_COPY,
} as const;
