const ZH_CN_HISTORY_COPY = {
  history: {
    title: "历史",
    sessionCount: (count: number) => `${count} 段会话`,
    pastSevenDays: "近 7 天",
    dailyHourlyActivity: "当日活动",
    appDistribution: "应用分布",
    noData: "暂无数据",
    timeline: "时间线",
    loading: "加载中...",
    emptyDay: "这一天暂无记录",
    activitySegmentCount: (count: number) => `活动 ${count}`,
    titleRowCount: (count: number) => `标题 ${count}`,
    titleDetails: "标题详情",
    untilNow: "至今",
    daySummary: "当日摘要",
    activeDuration: "活跃时长",
    activeSpan: "活跃跨度",
    peakHour: "高峰时段",
    showHourlyActivityByCategory: "按分类显示",
    showTotalHourlyActivity: "显示总活动",
    showTimelineByApp: "按应用显示",
    showTimelineByCategory: "按分类显示",
    dayDistribution: "当日分布",
    distributionByApp: "应用",
    distributionByCategory: "分类",
    distributionByWeb: "网页",
    timelineTabApp: "应用",
    timelineTabWeb: "网页",
    timelineAxis: "时间轴",
    openTimeline: "打开时间线",
    openTimelineZoom: "打开时间轴缩放",
    timelineZoom: "时间轴缩放",
    timelineWindowLabel: (start: string, end: string) => `${start} - ${end}`,
    emptyTimelineWindow: "当前时间段暂无记录",
    webTimelineUntitledPage: "无标题网页",
    horizontalTimeline: {
      ariaLabel: "横向日内时间轴",
      defaultTitle: "时间轴",
      emptyDay: "这一天暂无记录",
      remainingLegendItems: (count: number) => `+${count}`,
      remainingLegendItemsHint: (labels: string[]) => labels.join("、"),
    },
  },
};

const EN_US_HISTORY_COPY = {
  history: {
    title: "History",
    sessionCount: (count: number) => `${count} sessions`,
    pastSevenDays: "Last 7 days",
    dailyHourlyActivity: "Daily Activity",
    appDistribution: "App Distribution",
    noData: "No data",
    timeline: "Timeline",
    loading: "Loading...",
    emptyDay: "No records for this day",
    activitySegmentCount: (count: number) => `Act ${count}`,
    titleRowCount: (count: number) => `Titles ${count}`,
    titleDetails: "Title details",
    untilNow: "until now",
    daySummary: "Day Summary",
    activeDuration: "Active time",
    activeSpan: "Active span",
    peakHour: "Peak hour",
    showHourlyActivityByCategory: "Show by category",
    showTotalHourlyActivity: "Show total activity",
    showTimelineByApp: "Show by app",
    showTimelineByCategory: "Show by category",
    dayDistribution: "Day Distribution",
    distributionByApp: "Apps",
    distributionByCategory: "Categories",
    distributionByWeb: "Web",
    timelineTabApp: "Apps",
    timelineTabWeb: "Web",
    timelineAxis: "Day Timeline",
    openTimeline: "Open timeline",
    openTimelineZoom: "Open timeline zoom",
    timelineZoom: "Timeline zoom",
    timelineWindowLabel: (start: string, end: string) => `${start} - ${end}`,
    emptyTimelineWindow: "No records in this time range",
    webTimelineUntitledPage: "Untitled page",
    horizontalTimeline: {
      ariaLabel: "Horizontal daily timeline",
      defaultTitle: "Day Timeline",
      emptyDay: "No records for this day",
      remainingLegendItems: (count: number) => `+${count}`,
      remainingLegendItemsHint: (labels: string[]) => labels.join(", "),
    },
  },
};

export const historyCopy = {
  "zh-CN": ZH_CN_HISTORY_COPY,
  "en-US": EN_US_HISTORY_COPY,
} as const;
