const ZH_CN_MAPPING_COPY = {
  mapping: {
    title: "分类",
    subtitle: "设置应用和网页的分类、颜色与记录规则",
    saving: "正在保存...",
    saved: "已保存",
    idle: "已保存",
    unsaved: "有未保存更改",
    save: "保存",
    cancel: "取消",
    categoryControl: "管理分类",
    loading: "加载中...",
    emptyState: "当前筛选下暂无应用",
    webEmptyState: "当前筛选下暂无网页",
    searchPlaceholder: "搜索应用、网页或分类",
    appSearchPlaceholder: "搜索应用或分类",
    webSearchPlaceholder: "搜索网页或分类",
    objectModeApp: "应用",
    objectModeWeb: "网页",
    createCategoryTitle: "新建自定义分类",
    createCategoryDescription: "请输入自定义分类名称（最多 2 个字）。",
    createCategoryPlaceholder: "例如：学习",
    deleteCategoryTitle: "删除分类",
    deleteCategoryDetail: (label: string) => `目标分类：${label}`,
    deleteCategory: (label: string) => `删除分类：${label}`,
    deleteAppSessionsTitle: "删除应用记录",
    deleteAppSessionsDetail: (label: string) => `目标应用：${label}`,
    deleteWebDomainHistoryTitle: "删除网页记录",
    deleteWebDomainHistoryDetail: (label: string) => `目标网页：${label}`,
    filters: {
      all: "全部",
      other: "未分类",
      classified: "已分类",
    },
    categoryDialogTitle: "管理分类",
    categoryDialogDescription: "新建分类，调整分类颜色",
    createCategoryAction: "新建分类",
    editAppName: "修改应用名称",
    editWebDomainName: "修改网页名称",
    color: "颜色",
    restoreDefaultColor: "恢复默认颜色",
    noStats: "不计入统计",
    statsEnabled: "计入统计",
    titleNotRecorded: "不记录标题",
    titleRecorded: "记录标题",
    disableTitleCapture: "不记录该应用窗口标题",
    enableTitleCapture: "恢复记录该应用窗口标题",
    disableTracking: "将该应用排除出统计",
    enableTracking: "重新计入统计",
    disableWebTracking: "停止记录该网页",
    enableWebTracking: "恢复记录该网页",
    deleteAppRecords: "删除应用记录",
    deleteWebRecords: "删除网页记录",
  },
};

const EN_US_MAPPING_COPY = {
  mapping: {
    ...ZH_CN_MAPPING_COPY.mapping,
    title: "Classify",
    subtitle: "Set categories, colors, and recording rules for apps and websites",
    saving: "Saving...",
    saved: "Saved",
    idle: "Saved",
    unsaved: "Unsaved changes",
    save: "Save",
    cancel: "Cancel",
    categoryControl: "Manage categories",
    loading: "Loading...",
    emptyState: "No apps match the current filter",
    webEmptyState: "No websites match the current filter",
    searchPlaceholder: "Search apps, websites, or categories",
    appSearchPlaceholder: "Search apps or categories",
    webSearchPlaceholder: "Search websites or categories",
    objectModeApp: "Apps",
    objectModeWeb: "Web",
    createCategoryTitle: "New custom category",
    createCategoryDescription: "Enter one short category word.",
    createCategoryPlaceholder: "Example: Study",
    deleteCategoryTitle: "Delete category",
    deleteCategoryDetail: (label: string) => `Target category: ${label}`,
    deleteCategory: (label: string) => `Delete category: ${label}`,
    deleteAppSessionsTitle: "Delete app records",
    deleteAppSessionsDetail: (label: string) => `Target app: ${label}`,
    deleteWebDomainHistoryTitle: "Delete web records",
    deleteWebDomainHistoryDetail: (label: string) => `Target website: ${label}`,
    filters: {
      all: "All",
      other: "Unclassified",
      classified: "Classified",
    },
    categoryDialogTitle: "Manage categories",
    categoryDialogDescription: "Create categories and adjust category colors",
    createCategoryAction: "New category",
    editAppName: "Edit app name",
    editWebDomainName: "Edit website name",
    color: "Color",
    restoreDefaultColor: "Restore default color",
    noStats: "Excluded",
    statsEnabled: "Included",
    titleNotRecorded: "No title",
    titleRecorded: "Record title",
    disableTitleCapture: "Stop recording this app's window titles",
    enableTitleCapture: "Resume recording this app's window titles",
    disableTracking: "Exclude this app from statistics",
    enableTracking: "Include this app in statistics",
    disableWebTracking: "Stop recording this website",
    enableWebTracking: "Resume recording this website",
    deleteAppRecords: "Delete records",
    deleteWebRecords: "Delete web records",
  },
};

export const mappingCopy = {
  "zh-CN": ZH_CN_MAPPING_COPY,
  "en-US": EN_US_MAPPING_COPY,
} as const;
