const ZH_CN_TOAST_COPY = {
  toast: {
    releaseNotesOpenFailed: "无法打开发布说明链接。",
    repositoryOpenFailed: "无法打开 GitHub 链接。",
    feedbackOpenFailed: "无法打开反馈链接。",
    supportOpenFailed: "无法打开赞助链接。",
    settingsRuntimeSyncPartial: "设置已保存，部分运行时同步将在下次刷新后生效。",
    cleanupSuccess: "历史数据已清理。",
    cleanupFailed: "历史数据清理失败，请稍后重试。",
    backupExportSuccess: (path: string) => `备份已创建：${path}`,
    backupExportFailed: "备份失败，请检查路径后重试。",
    backupIncompatible: (reason?: string | null) => `备份不兼容：${reason ?? "无法确认兼容性"}`,
    backupPreviewFailed: "无法预览备份文件，请确认文件后重试。",
    backupRestoreSuccess: "备份已恢复，正在刷新界面。",
    backupRestoreFailed: "备份恢复失败，已自动回滚，不会破坏当前数据。",
    webDavConfigSaved: "WebDAV 配置已保存。",
    webDavConfigSaveFailed: "WebDAV 配置保存失败，请检查后重试。",
    webDavConfigDeleted: "WebDAV 配置已删除。",
    webDavConfigDeleteFailed: "WebDAV 配置删除失败，请稍后重试。",
    webDavMissingConfig: "请先配置 WebDAV 并保存密码。",
    webDavMissingPassword: "请输入 WebDAV 密码或应用密码。",
    webDavTestSuccess: "WebDAV 连接可用。",
    webDavTestFailed: "WebDAV 连接失败，请检查地址、账号和应用密码。",
    webDavUploadSuccess: (fileName: string) => `远程备份已上传：${fileName}`,
    webDavUploadIndexWarning: (fileName: string) => `远程备份已上传：${fileName}，但列表索引更新失败。`,
    webDavUploadFailed: "远程备份上传失败，本地数据未受影响。",
    webDavListFailed: "无法读取远程备份列表。",
    webDavDownloadFailed: "远程备份下载或恢复失败，本地数据未受影响。",
  },
};

const EN_US_TOAST_COPY = {
  toast: {
    releaseNotesOpenFailed: "Could not open release notes.",
    repositoryOpenFailed: "Could not open GitHub link.",
    feedbackOpenFailed: "Could not open feedback link.",
    supportOpenFailed: "Could not open support link.",
    settingsRuntimeSyncPartial: "Settings were saved. Some runtime changes will apply after the next refresh.",
    cleanupSuccess: "History records cleared.",
    cleanupFailed: "Could not clear history records. Try again later.",
    backupExportSuccess: (path: string) => `Backup created: ${path}`,
    backupExportFailed: "Could not create backup. Check the path and try again.",
    backupIncompatible: (reason?: string | null) => `Backup is incompatible: ${reason ?? "compatibility could not be confirmed"}`,
    backupPreviewFailed: "Could not preview this backup file. Check the file and try again.",
    backupRestoreSuccess: "Backup restored. Refreshing view.",
    backupRestoreFailed: "Backup restore failed. Changes were rolled back and current data is safe.",
    webDavConfigSaved: "WebDAV configuration saved.",
    webDavConfigSaveFailed: "Could not save WebDAV configuration. Check it and try again.",
    webDavConfigDeleted: "WebDAV configuration deleted.",
    webDavConfigDeleteFailed: "Could not delete WebDAV configuration. Try again later.",
    webDavMissingConfig: "Configure WebDAV and save the password first.",
    webDavMissingPassword: "Enter the WebDAV password or app password.",
    webDavTestSuccess: "WebDAV connection is available.",
    webDavTestFailed: "WebDAV connection failed. Check the address, username, and app password.",
    webDavUploadSuccess: (fileName: string) => `Remote backup uploaded: ${fileName}`,
    webDavUploadIndexWarning: (fileName: string) => `Remote backup uploaded: ${fileName}, but the list index could not be updated.`,
    webDavUploadFailed: "Remote backup upload failed. Local data was not changed.",
    webDavListFailed: "Could not read the remote backup list.",
    webDavDownloadFailed: "Remote backup download or restore failed. Local data was not changed.",
  },
};

export const toastCopy = {
  "zh-CN": ZH_CN_TOAST_COPY,
  "en-US": EN_US_TOAST_COPY,
} as const;
