const ZH_CN_UPDATE_COPY = {
  update: {
    appUpdate: "应用更新",
    sidebarEntry: "更新",
    releaseNotes: "更新说明",
    feedback: "问题反馈",
    support: "赞助项目",
    later: "稍后",
    manualDownload: "手动下载",
    downloadInstaller: "下载安装包",
    redownloadInstaller: "重新下载安装包",
    installAgain: "再次安装",
    checkAgain: "重新检查",
    checkUpdates: "检查更新",
    checkingUpdates: "正在检查更新...",
    checking: "检查中...",
    downloading: "正在下载更新...",
    installing: "正在安装更新...",
    processing: "处理中...",
    foundVersion: (version: string) => `发现新版本：${version}`,
    unknownVersion: "未知版本",
    updateReadyDetail: "新版本可用。确认后开始下载。",
    downloadNow: "立即下载",
    downloadedTitle: (version: string) => `更新已下载：${version}`,
    downloadedDetail: "更新包已下载。确认后重启安装。",
    restartInstall: "重启安装",
    targetVersion: (version: string) => `目标版本：${version}`,
    preparingPackage: "正在准备更新包。",
    installRestartDetail: "安装完成后应用会自动重启。",
    upToDate: "已是最新版本",
    notChecked: "未检查更新",
    checkFailed: "无法检查更新",
    downloadFailed: "无法下载安装包",
    installFailed: "更新安装失败",
    updateFailed: "更新失败",
    checkFailedDialog: "无法检查更新",
    downloadFailedDialog: "下载更新失败",
    installFailedDialog: "安装更新失败",
    updateFailedDialog: "更新失败",
    checkErrorDetail: "无法访问更新清单。当前网络可能无法连接 GitHub，你可以稍后重试，或手动下载。",
    downloadErrorDetail: "已发现新版本，但自动下载安装包失败。你可以手动下载。",
    installErrorDetail: "更新包已下载，但安装没有完成。你可以再次安装，或重新下载。",
    genericErrorDetail: "更新流程未能完成。你可以稍后重试。",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} 详细信息：${summary}`,
    downloadedBytes: (value: string) => `已下载 ${value}`,
    progressPending: "正在获取进度",
    packageDownloaded: (value?: string) => value ? `更新包 ${value} 已下载` : "更新包已下载",
    installingProgress: "正在安装更新，应用将很快重启",
    dialogInstalling: "正在安装更新",
    dialogDownloading: "正在下载更新",
    dialogDownloaded: "更新已下载",
    dialogAvailable: "发现新版本",
    dialogInstallingDetail: "更新安装已开始。请保持应用开启，完成后会自动重启。",
    dialogDownloadingDetail: "更新包正在下载，完成后会切换到安装确认。",
    dialogDownloadedDetail: "更新包已下载。确认后重启并完成安装。",
    dialogAvailableDetail: "新版本可用。确认后先下载更新包，下载完成后再确认安装。",
    updateProcessFailed: "更新流程未能完成。",
  },
};

const EN_US_UPDATE_COPY = {
  update: {
    appUpdate: "App updates",
    sidebarEntry: "Update",
    releaseNotes: "Release notes",
    feedback: "Feedback",
    support: "Sponsor",
    later: "Later",
    manualDownload: "Manual download",
    downloadInstaller: "Download installer",
    redownloadInstaller: "Download again",
    installAgain: "Install again",
    checkAgain: "Check again",
    checkUpdates: "Check updates",
    checkingUpdates: "Checking for updates...",
    checking: "Checking...",
    downloading: "Downloading update...",
    installing: "Installing update...",
    processing: "Processing...",
    foundVersion: (version: string) => `New version: ${version}`,
    unknownVersion: "unknown version",
    updateReadyDetail: "A new version is available. Confirm to start downloading.",
    downloadNow: "Download now",
    downloadedTitle: (version: string) => `Update downloaded: ${version}`,
    downloadedDetail: "The update package is downloaded. Confirm to restart and install.",
    restartInstall: "Restart to install",
    targetVersion: (version: string) => `Target version: ${version}`,
    preparingPackage: "Preparing the update package.",
    installRestartDetail: "The app will restart after installation.",
    upToDate: "You are up to date",
    notChecked: "Not checked",
    checkFailed: "Could not check updates",
    downloadFailed: "Could not download installer",
    installFailed: "Update installation failed",
    updateFailed: "Update failed",
    checkFailedDialog: "Could not check updates",
    downloadFailedDialog: "Download failed",
    installFailedDialog: "Install failed",
    updateFailedDialog: "Update failed",
    checkErrorDetail: "Could not access the update manifest. Your current network may not be able to reach GitHub. Try again later or download manually.",
    downloadErrorDetail: "A new version was found, but automatic download failed. You can download manually.",
    installErrorDetail: "The update package was downloaded, but installation did not finish. Try installing again or redownload it.",
    genericErrorDetail: "The update flow could not finish. Try again later.",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} Details: ${summary}`,
    downloadedBytes: (value: string) => `Downloaded ${value}`,
    progressPending: "Getting progress",
    packageDownloaded: (value?: string) => value ? `Package ${value} downloaded` : "Package downloaded",
    installingProgress: "Installing update. The app will restart soon.",
    dialogInstalling: "Installing update",
    dialogDownloading: "Downloading update",
    dialogDownloaded: "Update downloaded",
    dialogAvailable: "New version available",
    dialogInstallingDetail: "Installation has started. Keep the app open; it will restart when finished.",
    dialogDownloadingDetail: "The update package is downloading. Installation confirmation appears when it finishes.",
    dialogDownloadedDetail: "The update package is ready. Confirm to restart and finish installation.",
    dialogAvailableDetail: "A new version is available. Download first, then confirm installation.",
    updateProcessFailed: "The update flow could not finish.",
  },
};

export const updateCopy = {
  "zh-CN": ZH_CN_UPDATE_COPY,
  "en-US": EN_US_UPDATE_COPY,
} as const;
